### ISSUE TITLE
queryKNN returns empty list() which may cause bug in SingleR

### ISSUE THREAD

**Issue by mimi3421** [LTLA/kmknn#8] opened 2019-09-17 05:35 UTC
Dear author,
Dose queryKNN return any meaningful value when parameters get.index and get.distance are set to FALSE?

I have recently tried SingleR package and gotten the following error:
```
Error in nn.d^2 : non-numeric argument to binary operator
```

I looked into the codes and found that the error may be due to the following codes in SingleR/R/classifySingleR.R where queryKNN always returns an empty _list()_:
``` {r}
.find_nearest_quantile <- function(ranked, index, quantile) {
    k <- max(1, round(nrow(index) * (1-quantile)))
    nn.d <- queryKNN(query=ranked, k=k, BNINDEX=index, get.index=FALSE, get.distance=FALSE)
    1 - 2*nn.d^2 # see https://arxiv.org/abs/1208.3145
}
```

Sorry to bring up an issue about SingleR here because I don't know how to put issues in bioconductor. Thanks for sharing these beautiful packages.

**Comment by LTLA** [comment] 2019-09-17 05:48
This is a temporary error caused by the fact that _BiocNeighbors_ was updated but _SingleR_ was not. If you sit tight, it should fix itself with version 0.99.12 of _SingleR_. Or you can pull it from GitHub.

For future reference, questions about Bioconductor packages should go [here](https://support.bioconductor.org).

**Comment by AJnsm** [comment] 2019-09-17 15:54
I can confirm that installing 0.99.12 from GitHub solves this issue.

**Comment by LTLA** [comment] 2019-09-18 23:58
This should be fixed on BioC as well.

**Closed as completed by LTLA** 2019-09-18 23:58 UTC
